spring:
  application:
    name: basic-board
  datasource:
    url: jdbc:mysql://localhost:3306/java_basic?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: programmers
    password: password1234
  file:
    upload-dir: ./uploads

